version: '3.8'

services:
  langchain_app:
    build: ./backend
    container_name: langchain_app
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: ${DB_HOST:-mysql}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-rootpassword}
      DB_NAME: ${DB_NAME:-dev_tas_live}
      DB_PORT: ${DB_PORT:-3306}
      PYTHONPATH: /app
      ENABLE_PII_FILTERING: ${ENABLE_PII_FILTERING:-true}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - my_workspace
    depends_on:
      - mysql
    command: [
      "sh",
      "-c",
      "find /app -type f -name '*.pyc' -delete && find /app -type d -name '__pycache__' -exec rm -r {} + && cd /app && python -m uvicorn server:app --host 0.0.0.0 --port 8000"
    ]

  mysql:
    image: mysql:8.0
    container_name: langchain_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-sakila}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - my_workspace
    command: --default-authentication-plugin=mysql_native_password

  frontend:
    build: ./frontend
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - my_workspace
    stdin_open: true
    tty: true

networks:
  my_workspace:
    name: my_workspace

volumes:
  mysql_data:
