version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
    depends_on:
      - langchain_app
    networks:
      - teladoc_docker_env

  langchain_app:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=mysql+pymysql://root:@mysql:3306/dev_tas_live
    networks:
      - teladoc_docker_env

  mysql_test:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dev_tas_live
    ports:
      - "3307:3306"
    volumes:
      - ./backend/test_schema.sql:/docker-entrypoint-initdb.d/test_schema.sql
    networks:
      - teladoc_docker_env

  frontend_test:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true
    command: npm test -- --watchAll=false
    depends_on:
      - langchain_app
    networks:
      - teladoc_docker_env

networks:
  teladoc_docker_env:
    external: true
