version: '3.8'

services:
  langchain_app:
    build: ./backend
    container_name: langchain_app
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Any other env variables you need
    volumes:
      - .:/app  # mount local code
    ports:
      - "8000:8000"
    networks:
      - teladoc_docker_env
    command: [
      "python",
      "-m",
      "uvicorn",
      "backend.langchain_mysql:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "--reload"
    ]

networks:
  teladoc_docker_env:
    external: true
