version: '3.8'

services:
<<<<<<< Updated upstream
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=4000
    depends_on:
      - langchain_app
    networks:
      - teladoc_docker_env

  langchain_app:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=mysql+pymysql://root:@mysql:3306/dev_tas_live
    networks:
      - teladoc_docker_env

  mysql_test:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dev_tas_live
    ports:
      - "3307:3306"
    volumes:
      - ./backend/test_schema.sql:/docker-entrypoint-initdb.d/test_schema.sql
    networks:
      - teladoc_docker_env

  frontend_test:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true
    command: npm test -- --watchAll=false
    depends_on:
      - langchain_app
    networks:
      - teladoc_docker_env
=======
  langchain_app:
    build: ./backend
    container_name: langchain_app
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: ${DB_HOST:-mysql}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-rootpassword}
      DB_NAME: ${DB_NAME:-dev_tas_live}
      DB_PORT: ${DB_PORT:-3306}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - teladoc_docker_env
    depends_on:
      - mysql
    command: [
      "python",
      "-m",
      "uvicorn",
      "backend.langchain_mysql:app",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "--reload"
    ]

  mysql:
    image: mysql:8.0
    container_name: langchain_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-sakila}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - teladoc_docker_env
    command: --default-authentication-plugin=mysql_native_password

  frontend:
    build: ./frontend
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    networks:
      - teladoc_docker_env
    stdin_open: true
    tty: true
>>>>>>> Stashed changes

networks:
  teladoc_docker_env:
    external: true

volumes:
  mysql_data:
