version: '3.8'

services:
  langchain_app:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - .:/app  # Mount your local project directory to /app in the container
    ports:
      - "8000:8000"
    networks:
      - teladoc_docker_env
    command: ["python", "-m", "uvicorn", "langchain_mysql:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  teladoc_docker_env:
    external: true  # Use an already existing network
