version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: testpassword
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql+pymysql://test_user:testpassword@mysql:3306/test_db
      OPENAI_API_KEY: test_key
      PYTHONPATH: /app:/app/src:/app/backend/src
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "cd /app && python -m pytest tests/ -v --import-mode=importlib" 
