INCLUDED_TABLES = [
    "consultations",
    "members",
    "persons",
    "invoices",
    "invoice_items",
    "provider_panel_extensions",
    "member_provider_relations",
    "care_team_relations",
    "consult_statuses",
    "parties",
    "party_addresses",
    "clinical_notes",
    "clinical_diagnoses",
    "clinical_documents",
]
